name: Publish on tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Create package
        run: tar -czf package.tgz dist/
      - name: Upload package to artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package.tgz
  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download package from artifact
        uses: actions/download-artifact@v3
        with:
          name: package
      - run: tar -xzf package.tgz
      - run: npm publish dist/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  # publish-gpr:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Authenticate with the GitHub Package Registry
  #       uses: actions/authenticate-with-github-package-registry@v1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Download package from artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: package
  #     - run: tar -xzf package.tgz
  #     - run: npm publish dist/ --registry=https://npm.pkg.github.com/OWNER
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
